If you want to type along with me, head to [this notebook](https://humboldt.cloudbank.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fbethanyj0%2Fdata111_fa24&branch=main&urlpath=lab%2Ftree%2Fdata111_fa24%2Flectures%2Flec05_live.ipynb) instead. If you prefer follow along by executing the cells, stay in this notebook.

In [1]:
from datascience import *
import numpy as np

## Arrays Recap and more ##

In [2]:
first_four = make_array(1, 2, 3, 4)

In [3]:
first_four

array([1, 2, 3, 4])

In [4]:
first_four * 2

array([2, 4, 6, 8])

In [5]:
first_four ** 2

array([ 1,  4,  9, 16])

In [6]:
type(first_four)

numpy.ndarray

In [7]:
next_four = make_array(5, 6, 7, 8)

In [8]:
first_four + next_four

array([ 6,  8, 10, 12])

In [9]:
only_three = make_array(5, 6, 7)

In [10]:
# This line will cause an error 
first_four + only_three

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [11]:
min(first_four)

1

In [12]:
first_four # array is unchanged, just like when we call show/select/drop on Table

array([1, 2, 3, 4])

In [13]:
str_array = make_array('ha', 'he', 'ho')

In [14]:
# Check the number of elements
len(str_array)

3

In [15]:
make_array(1.0,2,3)

array([ 1.,  2.,  3.])

In [16]:
make_array('ha',2,3)

array(['ha', '2', '3'],
      dtype='<U21')

In [17]:
first_four.item(0)

1

In [18]:
first_four.item(1)

2

In [19]:
# Select the last item
first_four.item(-1)

4

In [20]:
sum(first_four)

10

In [21]:
np.average(first_four)

2.5

**Activity** What is the average of all *even* numbers between 2 and 16 (inclusive)?

## Columns of Tables are Arrays ##

In [22]:
nba = Table.read_table('nba_salaries.csv').where('season', 2020).drop('season')
nba.show(5)

In [23]:
nba.num_rows

528

In [24]:
nba.num_columns

5

In [25]:
nba.labels

('rank', 'name', 'position', 'team', 'salary')

In [26]:
warriors = nba.where('team', 'Golden State Warriors')
warriors.show(5)

In [27]:
warriors.relabeled('salary', '$')

rank | name                | position | team                  | $
1    | Stephen Curry       | PG       | Golden State Warriors | 40231758
13   | Klay Thompson       | SG       | Golden State Warriors | 32742000
60   | Draymond Green      | PF       | Golden State Warriors | 18539130
223  | Kevon Looney        | PF       | Golden State Warriors | 4464226
316  | Willie Cauley-Stein | C        | Golden State Warriors | 2177483
332  | Jordan Poole        | SG       | Golden State Warriors | 1964760
339  | Omari Spellman      | PF       | Golden State Warriors | 1897800
496  | Alen Smailagic      | PF       | Golden State Warriors | 898310
497  | Eric Paschall       | PF       | Golden State Warriors | 898310
502  | Damion Lee          | SG       | Golden State Warriors | 842327
... (3 rows omitted)

In [28]:
warriors

rank | name                | position | team                  | salary
1    | Stephen Curry       | PG       | Golden State Warriors | 40231758
13   | Klay Thompson       | SG       | Golden State Warriors | 32742000
60   | Draymond Green      | PF       | Golden State Warriors | 18539130
223  | Kevon Looney        | PF       | Golden State Warriors | 4464226
316  | Willie Cauley-Stein | C        | Golden State Warriors | 2177483
332  | Jordan Poole        | SG       | Golden State Warriors | 1964760
339  | Omari Spellman      | PF       | Golden State Warriors | 1897800
496  | Alen Smailagic      | PF       | Golden State Warriors | 898310
497  | Eric Paschall       | PF       | Golden State Warriors | 898310
502  | Damion Lee          | SG       | Golden State Warriors | 842327
... (3 rows omitted)

In [29]:
warriors = nba.where('team', 'Golden State Warriors').drop('team').relabeled('salary', '$')
warriors.show(3)

In [30]:
warriors.select('$')

$
40231758
32742000
18539130
4464226
2177483
1964760
1897800
898310
898310
842327
... (3 rows omitted)

In [31]:
type(warriors.select('$'))

datascience.tables.Table

In [32]:
# This will produce an error
np.average(warriors.select('$'))

IndentationError: unexpected indent (3356145488.py, line 2)

In [33]:
warriors.column('$')

array([40231758, 32742000, 18539130,  4464226,  2177483,  1964760,
        1897800,   898310,   898310,   842327,   654469,   350189,   350189])

In [34]:
type(warriors.column('$'))

numpy.ndarray

In [35]:
np.average(warriors.column('$'))

8154688.538461538

In [36]:
# another way
warriors.column(3)

array([40231758, 32742000, 18539130,  4464226,  2177483,  1964760,
        1897800,   898310,   898310,   842327,   654469,   350189,   350189])

In [37]:
suns = nba.where('team', 'Phoenix Suns').drop('team').relabeled('salary', '$')

In [38]:
np.average(warriors.column('$')) - np.average(suns.column('$'))

2393314.5910931174

In [39]:
np.sum(warriors.column('$')) - np.sum(suns.column('$'))

-3455154

**Activity:** What was the average rank of players on the Golden State Warriors in 2020?

In [56]:
np.average(warriors.column('rank'))

332.92307692307691

In [40]:
# A note about taking rows
nba.take(0)

rank | name          | position | team                  | salary
1    | Stephen Curry | PG       | Golden State Warriors | 40231758

## Ranges ##

In [41]:
make_array(0, 1, 2, 3, 4, 5, 6)

array([0, 1, 2, 3, 4, 5, 6])

In [42]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [43]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [44]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [46]:
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

**Activity:** How many odd numbers are there between 5 and 75 (inclusive)?
*Hint* Create the relevant array then apply a function to determine how many elements are in it.  

In [55]:
len(np.arange(5,76,2))

36

# Ways to Create a Table #

## Creating a Table from Scratch ##

In [ ]:
streets = make_array('14th', '13th', '12th', '11th')
streets

In [ ]:
Table()

In [ ]:
southside = Table().with_column('Streets', streets)
southside

In [ ]:
southside.with_column('Blocks from campus', np.arange(4))

In [ ]:
southside

In [ ]:
southside = southside.with_column('Blocks from campus', np.arange(4))
southside

In [ ]:
Table().with_columns(
    'Streets', streets,
    'Blocks from campus', np.arange(4)
)

## Reading a Table from a File  ##

In [57]:
du_bois = Table.read_table('du_bois.csv')
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

In [58]:
du_bois.column('ACTUAL AVERAGE')

array([  139.1 ,   249.45,   335.66,   433.82,   547.  ,   880.  ,  1125.  ])

In [59]:
du_bois.column('FOOD')

array([ 0.43,  0.47,  0.43,  0.37,  0.31,  0.37,  0.29])

In [60]:
du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')

array([  59.813 ,  117.2415,  144.3338,  160.5134,  169.57  ,  325.6   ,
        326.25  ])

In [61]:
food_dollars = du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')
du_bois.with_column('Food $', food_dollars)

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS      | Food $
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR        | 59.813
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR        | 117.241
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR        | 144.334
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR        | 160.513
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25

In [62]:
du_bois = du_bois.with_column('Food $', food_dollars)
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS      | Food $
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR        | 59.813
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR        | 117.241
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR        | 144.334
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR        | 160.513
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25

In [63]:
np.max(du_bois.column('Food $'))

326.25

In [64]:
du_bois.with_column(
    'Fraction of well-to-do food $', 
    du_bois.column('Food $') / np.max(du_bois.column('Food $')))

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS      | Food $  | Fraction of well-to-do food $
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR        | 59.813  | 0.183335
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR        | 117.241 | 0.359361
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR        | 144.334 | 0.442402
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR        | 160.513 | 0.491995
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57  | 0.519755
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6   | 0.998008
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25  | 1

**Activity:** Use table functions we learned this week to find the income bracket (“class”) that spent the highest proportion of income on rent. 

In [67]:
du_bois.sort('RENT',descending=True).column('CLASS').take(0)

'300-400'

## Where Method

In [ ]:
nba.where('position', are.containing('G'))

## Print and string formatting

In [ ]:
1 + 2
3 + 4

In [ ]:
print(1 + 2)
print(3 + 4)

In [ ]:
'Go Humboldt!'

In [ ]:
print('Go Humboldt!')

In [ ]:
cph = 'Cal Poly Humboldt'

In [ ]:
'{cph} is awesome'

In [ ]:
f'{cph} is awesome'

In [ ]:
print(f'{cph} is awesome!')
print(f'{warriors.column("name").item(0)} is pretty awesome too!')